# Generated by Django 2.1.1 on 2018-09-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorders',
            name='orderedBy',
        ),
    ]
