# Generated by Django 2.1.1 on 2018-09-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_userorders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorders',
            name='user',
        ),
    ]
