# Generated by Django 2.1.1 on 2018-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_userorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='orderedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.UserProfileInfo'),
        ),
    ]
