# Generated by Django 2.1.1 on 2018-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20180929_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
